In [2]:
import torch
torch.cuda.is_available()

True

In [4]:
# creates a tensor with values which were already in the memory
torch.empty(2,3)

tensor([[-2.3446e-02,  9.3607e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [5]:
type(torch.empty(2,3))

torch.Tensor

In [8]:
# zero tensor
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# ones tensor
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# random values
torch.rand(2,3)

tensor([[0.9599, 0.5918, 0.7752],
        [0.8028, 0.1484, 0.5616]])

In [11]:
# to keep rand output same, use manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# your own tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
# other ways

print("torch.arange(0,10,2): ",torch.arange(0,10,2))
print("torch.linspace(0,10,10): ",torch.linspace(0,10,10))
print("torch.eye(5): ",torch.eye(5))
print("torch.full((3,3),5): ",torch.full((3,3),5))

torch.arange(0,10,2):  tensor([0, 2, 4, 6, 8])
torch.linspace(0,10,10):  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
torch.eye(5):  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
torch.full((3,3),5):  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [27]:
# shape
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [28]:
# creating new tensor with shape same as some other tensor
torch.empty_like(x)

tensor([[      2872204986336, 4635705220378015972, 4661726013461248228],
        [4681742012764214613, 4692750812811507940,                   0]])

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# code breaks
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [38]:
# x has int while rand gives floats between 0 and 1,
# so you need to tell rand that you need float values
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [34]:
# tensor data type
x.dtype

torch.int64

In [35]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [37]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [39]:
# mathematical operations

In [42]:
x=torch.rand(2,2)

In [43]:
x

tensor([[0.1629, 0.8902],
        [0.5163, 0.0359]])

In [44]:
x+2

tensor([[2.1629, 2.8902],
        [2.5163, 2.0359]])

In [45]:
x-2

tensor([[-1.8371, -1.1098],
        [-1.4837, -1.9641]])

In [46]:
x*3

tensor([[0.4886, 2.6706],
        [1.5488, 0.1077]])

In [47]:
x/3

tensor([[0.0543, 0.2967],
        [0.1721, 0.0120]])

In [48]:
(x*100)//3

tensor([[ 5., 29.],
        [17.,  1.]])

In [49]:
((x*100)//3)%2

tensor([[1., 1.],
        [1., 1.]])

In [50]:
# element wise operations

In [51]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])
tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])


In [52]:
a+b

tensor([[1.5527, 0.9419, 0.7632],
        [1.2539, 0.5009, 0.8512]])

In [53]:
a-b

tensor([[-0.2574, -0.2558, -0.1268],
        [-0.2017, -0.4116,  0.1735]])

In [54]:
a*b

tensor([[0.5862, 0.2054, 0.1416],
        [0.3829, 0.0204, 0.1736]])

In [55]:
a/b

tensor([[0.7156, 0.5728, 0.7151],
        [0.7228, 0.0979, 1.5119]])

In [56]:
a**b

tensor([[0.6749, 0.5269, 0.6008],
        [0.6266, 0.2421, 0.7972]])

In [57]:
a%b

tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.1735]])

In [58]:
c=torch.tensor([1.9,-2.3,3.7,-3.2])

In [59]:
torch.abs(c)

tensor([1.9000, 2.3000, 3.7000, 3.2000])

In [60]:
torch.neg(c)

tensor([-1.9000,  2.3000, -3.7000,  3.2000])

In [61]:
torch.round(c)

tensor([ 2., -2.,  4., -3.])

In [62]:
torch.ceil(c)

tensor([ 2., -2.,  4., -3.])

In [63]:
torch.floor(c)

tensor([ 1., -3.,  3., -4.])

In [65]:
torch.clamp(c,min=1,max=3)

tensor([1.9000, 1.0000, 3.0000, 1.0000])

In [75]:
c=torch.randint(size=(2,3),low=0,high=10, dtype=torch.float32)
c

tensor([[8., 3., 3.],
        [5., 0., 6.]])

In [76]:
torch.sum(c)

tensor(25.)

In [77]:
# col wise sum
torch.sum(c,dim=0)

tensor([13.,  3.,  9.])

In [78]:
# row wise sum
torch.sum(c,dim=1)

tensor([14., 11.])

In [80]:
# only works on float
torch.mean(c)

tensor(4.1667)

In [81]:
torch.mean(c, dim=0)

tensor([6.5000, 1.5000, 4.5000])

In [82]:
torch.mean(c, dim=1)

tensor([4.6667, 3.6667])

In [83]:
torch.median(c)

tensor(3.)

In [84]:
torch.max(c)

tensor(8.)

In [85]:
torch.min(c)

tensor(0.)

In [86]:
torch.prod(c)

tensor(0.)

In [87]:
torch.std(c)

tensor(2.7869)

In [88]:
torch.var(c)

tensor(7.7667)

In [89]:
torch.argmax(c)

tensor(0)

In [91]:
torch.argmin(c)

tensor(4)

In [92]:
# matrix operations

In [93]:
a=torch.randint(size=(2,3),low=0,high=10)
b=torch.randint(size=(3,2),low=0,high=10)
print(a)
print(b)

tensor([[4, 0, 8],
        [4, 7, 2]])
tensor([[3, 8],
        [5, 6],
        [2, 9]])


In [ ]:
# matrix multiplication
torch.matmul(a,b)

tensor([[ 28, 104],
        [ 51,  92]])

In [96]:
a=torch.tensor([1,2])
b=torch.tensor([3,4])

torch.dot(a,b)

tensor(11)

In [97]:
torch.transpose(c,0,1)

tensor([[8., 5.],
        [3., 0.],
        [3., 6.]])

In [100]:
a=torch.rand(size=(3,3))
torch.det(a)

tensor(0.3735)

In [101]:
torch.inverse(a)

tensor([[ 1.7346, -0.5434, -0.3503],
        [-1.9914,  2.0029,  0.1461],
        [-0.3530, -0.2356,  1.2548]])

In [102]:
# comparisons

In [110]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [111]:
a<b

tensor([[False,  True,  True],
        [ True,  True,  True]])

In [112]:
a>b

tensor([[ True, False, False],
        [False, False, False]])

In [113]:
a==b

tensor([[False, False, False],
        [False, False, False]])

In [114]:
# special functions

In [121]:
a=torch.randint(size=(2,3),low=0,high=10, dtype=torch.float32)

In [122]:
torch.log(a)

tensor([[  -inf, 1.9459, 2.1972],
        [0.6931, 1.9459,   -inf]])

In [123]:
torch.exp(a)

tensor([[1.0000e+00, 1.0966e+03, 8.1031e+03],
        [7.3891e+00, 1.0966e+03, 1.0000e+00]])

In [124]:
torch.sqrt(a)

tensor([[0.0000, 2.6458, 3.0000],
        [1.4142, 2.6458, 0.0000]])

In [125]:
torch.sigmoid(a)

tensor([[0.5000, 0.9991, 0.9999],
        [0.8808, 0.9991, 0.5000]])

In [126]:
torch.softmax(a,dim=0)

tensor([[1.1920e-01, 5.0000e-01, 9.9988e-01],
        [8.8080e-01, 5.0000e-01, 1.2339e-04]])

In [127]:
torch.relu(a)

tensor([[0., 7., 9.],
        [2., 7., 0.]])

In [128]:
# inplace operations

In [129]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.8993, 0.2732, 0.3397],
        [0.1879, 0.5534, 0.2682]])
tensor([[0.9556, 0.9761, 0.5934],
        [0.3124, 0.9431, 0.8519]])


In [131]:
# this creates a new tensor
m+n

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [ ]:
# this does inplace, _ is added in inplace operations
m.add_(n)

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [133]:
m

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [134]:
m.relu_()

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [135]:
m

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [136]:
# copying a tensor

In [137]:
a=torch.rand(2,3)
a

tensor([[0.9815, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [138]:
b=a

In [139]:
b

tensor([[0.9815, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [140]:
# but simply assigning binds a with b
a[0][0]=0
b

tensor([[0.0000, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [142]:
id(a)

2128664617968

In [143]:
id(b)

2128664617968

In [144]:
# true copy
b=a.clone()

In [145]:
id(a)

2128664617968

In [146]:
id(b)

2128797538000

In [147]:
# tensor operations on gpu

In [148]:
torch.cuda.is_available()

True

In [149]:
device=torch.device('cuda')

In [150]:
# creating a tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [152]:
# moving existing tensor on gpu
a=torch.rand(2,3)
b=a.to(device)
b

tensor([[0.4603, 0.1386, 0.0277],
        [0.5662, 0.3503, 0.6555]], device='cuda:0')

In [153]:
# reshaping tensors

In [154]:
a=torch.ones(4,4)

In [155]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [156]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [158]:
b=torch.rand(2,3,4)
b

tensor([[[0.4947, 0.3617, 0.9687, 0.0359],
         [0.3041, 0.9867, 0.1290, 0.6887],
         [0.1637, 0.0899, 0.3139, 0.1219]],

        [[0.3516, 0.2316, 0.2847, 0.3520],
         [0.2828, 0.2420, 0.4928, 0.5772],
         [0.3771, 0.2440, 0.8994, 0.1041]]])

In [163]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [170]:
# unsqueeze adds a new dimension at the given index
c=torch.rand(226,226,3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [177]:
# squeeze removes a dimension
d=torch.rand(1,20,20)
d.squeeze(0).shape

torch.Size([20, 20])

In [178]:
# numpy and pytorch

In [179]:
import numpy as np

In [180]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [181]:
b=a.numpy()
b

array([1, 2, 3], dtype=int64)

In [182]:
type(b)

numpy.ndarray

In [183]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [184]:
torch.from_numpy(c)

tensor([1, 2, 3], dtype=torch.int32)